version: "1.0"

services:
  action-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: ["rasa", "run", "actions"]
    ports:
      - "5055:5055"
    public: true
    networks:
      - all

  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf /app/models/* && rasa train && rasa run --enable-api --cors \"*\" --debug -p 5005"
    ports:
      - "5005:5005"
    public: true
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
