# Generated by Django 4.2.1 on 2023-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField(max_length=3)),
                ('P', models.IntegerField(max_length=3)),
                ('K', models.IntegerField(max_length=3)),
                ('temperature', models.FloatField(max_length=4)),
                ('humidity', models.FloatField(max_length=4)),
                ('ph', models.FloatField(max_length=4)),
                ('rainfall', models.FloatField(max_length=4)),
                ('result', models.CharField(max_length=255)),
                ('ml', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('FeedBack', models.CharField(max_length=255)),
            ],
        ),
    ]
